# Generated by Django 3.2.4 on 2021-11-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_alter_review_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
