# Generated by Django 3.2.4 on 2022-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0004_auto_20211111_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
