# Generated by Django 3.2.4 on 2021-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(choices=[('gangnam', '강남구'), ('gangdong', '강동구'), ('gwangjin', '광진구'), ('mapo', '마포구'), ('seocho', '서초구'), ('yangchun', '양천구')], max_length=100),
        ),
    ]
