# Generated by Django 3.2.4 on 2021-11-23 15:39

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price_desc_extra',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[shop.validators.validate_file_size]),
        ),
    ]
