# Generated by Django 3.2.4 on 2021-11-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0004_auto_20211111_0229'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.review'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(0, 'inquiry'), (1, 'confirmed'), (2, 'reviewed'), (3, 'unreviewed')]),
        ),
    ]
