# Generated by Django 3.2.4 on 2022-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20211111_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(0, 'inquiry'), (1, 'confirmed'), (2, 'reviewed'), (3, 'unreviewed'), (4, 'invalid')]),
        ),
    ]
